fix exports missing createDigestClient method
seems to work now after getting errors

TypeError: Object function createDigestClient(username, password, https) {
  return new HTTPDigest(username, password, https);
} has no method 'createDigestClient'